### ISSUE TITLE
[2.0] Current status of development

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/laravel-page-view-counter#46]
# v2.0.0

## Main Goals

The main goals are:

* Cache retrieved views count
* API refactoring
* Ignore bots
* Cover the package with tests
* _Rename package to `Eloquent Viewable`_

## Development

**Branch:** 2.0
**Migration possible:** yes

### Tasks statuses

- [x] Cache retrieved views count.
- [x] API refactoring & Package renaming.
- [x] Ignore bots.
- [x] Add option to ignore visitors with `HTTP_DNT` header.
- [x] Instead of trusting IP addresses, move on to cookies.
- [x] Improve `countViews()` in `ViewableService.php`.
- [x] Make the View model extendable via bindings, instead of using the config.
- [x] Save the cookie via routes (improvement).
- [x] Add scopes to the trait to allow ordering by most views.
- [x] Finish the contract interfaces.
- [x] Be able to skip views of IP addresses

#### Why?

Since every page view is stored as a seperate entity in the database, counting the views can be a time consuming task. So instead, we could cache views counts in the cache to reduce the amount of queries.

#### How?

While the whole idea of caching sounds quite simple, it is harder than I thought. The way I would cache views counts is saving the number of views under a unique key that's created based upon the since date, upto date and if the views should be unique. The structure of this key is: `<package prefix>.counts.<model type>.<model id>.<request type: normal | unique>.<request period: <since?>|<upto?>>`.

| Segment name | Description |
|------------------|--------------|
| package prefix | Default: 'cyrildewit.eloquent-viewable'. This can be changed in the config file.
| model type       | The class namespace of the viewable model |
| model id           | The primary id of the viewable model |
| request type     | Default: 'normal'. Unique views: 'unique' |
| request period  | The structure of this part is: '<since?>\|<upto?>'. <br>If the given date is reactive (like past 3 days or past 2 weeks) they will not be stored as a date string |

#### Viewable trait

**Old**

```php
$article->getPageViews();
$article->getUniquePageViews();
$article->getPageViewsFrom($sinceDate);
$article->getUniquePageViewsFrom($sinceDate);
$article->getPageViewsBefore($uptoDate);
$article->getUniquePageViewsBefore($uptoDate);
$article->getPageViewsBetween($sinceDate, $uptoDate);
$article->getUniquePageViewsBetween($sinceDate, $uptoDate);
```

**New**

```php
$article->getViews();
$article->getUniqueViewsSince();
$article->getViewsSince($sinceDate);
$article->getUniqueViewsSince($sinceDate);
$article->getViewsUpto($uptoDate);
$article->getUniqueViewsUpto($uptoDate);
$article->getViewsBetween($sinceDate, $uptoDate);
$article->getUniqueViewsBetween($sinceDate, $uptoDate);

// New
$article->getViewsOfPastSeconds();
$article->getViewsOfPastMinutes();
$article->getViewsOfPastDays();
$article->getViewsOfPastWeeks();
$article->getViewsOfPastMonths();
$article->getViewsOfPastYears();
```

#### Unit Tests

* [x] Viewable trait (`CyrildeWit\EloquentViewable\Traits\Viewable`)
* [x] ViewableService class (`CyrildeWit\EloquentViewable\Services\ViewableService`)
* [x] View class (`CyrildeWit\EloquentViewable\Models\View`)
* [x] ViewableObserver class (`CyrildeWit\EloquentViewable\Observers\ViewableObserver`)
* [x] CrawlerDetector interface (`CyrildeWit\EloquentViewable\Contracts\CrawlerDetector`)
* [x] Period class (`CyrildeWit\EloquentViewable\Support\Period`)
* [x] ViewTeacker class (`CyrildeWit\EloquentViewable\ViewTracker`)

**Comment by AdrienPoupa** [comment]
Hello,
Will it be possible to upgrade from 1.x?

**Comment by cyrildewit** [comment]
@AdrienPoupa yes, but it will take some time. You will not loose the visits, because the table structure remain the same. The package will be renamed, so installing the new published package is required. And you will have to replace the methods with their new names.

I will try to write a upgrade guide when I am done with v2. It will take a while before it comes out, so you can use v1 for now.

**Comment by AdrienPoupa** [comment]
Good, I was mainly concerned about the data. Thank you!
